// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJYzlmzg5QHxPg45utWF3rOkAqHQ5fdpA',
    appId: '1:281962672835:android:12174c303e193376c62876',
    messagingSenderId: '281962672835',
    projectId: 'petdata-dad1c',
    storageBucket: 'petdata-dad1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFWKd7WC_FdJ0uHAJ3P0kmcOiOt36qCRE',
    appId: '1:281962672835:ios:18625d8298f09a0dc62876',
    messagingSenderId: '281962672835',
    projectId: 'petdata-dad1c',
    storageBucket: 'petdata-dad1c.appspot.com',
    iosClientId: '281962672835-mvelho8lkecgksilp6kahocgnue1i0j3.apps.googleusercontent.com',
    iosBundleId: 'com.jkta.petHealthyProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFWKd7WC_FdJ0uHAJ3P0kmcOiOt36qCRE',
    appId: '1:281962672835:ios:d4e13979ec9fbe60c62876',
    messagingSenderId: '281962672835',
    projectId: 'petdata-dad1c',
    storageBucket: 'petdata-dad1c.appspot.com',
    iosClientId: '281962672835-q5f03j13mkqcjlh6bbandrbo5c72mqlf.apps.googleusercontent.com',
    iosBundleId: 'com.jkta.petHealthyProj.RunnerTests',
  );
}
